// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../../core/resource';
import * as ContactsAPI from './contacts';
import {
  Contact,
  ContactBulkCreateParams,
  ContactBulkCreateResponse,
  ContactBulkDeleteParams,
  ContactBulkDeleteResponse,
  ContactBulkUpdateParams,
  ContactBulkUpdateResponse,
  ContactCountParams,
  ContactCountResponse,
  ContactCreateParams,
  ContactCreateResponse,
  ContactDeleteParams,
  ContactDuplicateParams,
  ContactDuplicateResponse,
  ContactFindParams,
  ContactFindResponse,
  ContactGetParams,
  ContactGetResponse,
  ContactListParams,
  ContactListResponse,
  ContactQueryParams,
  ContactQueryResponse,
  ContactRestoreParams,
  ContactRestoreResponse,
  ContactUpdateParams,
  ContactUpdateResponse,
  ContactUpsertParams,
  ContactUpsertResponse,
  Contacts,
} from './contacts';
import * as IdentitiesAPI from './identities';
import {
  Identities,
  Identity,
  IdentityBulkCreateParams,
  IdentityBulkCreateResponse,
  IdentityBulkDeleteParams,
  IdentityBulkDeleteResponse,
  IdentityBulkUpdateParams,
  IdentityBulkUpdateResponse,
  IdentityCountParams,
  IdentityCountResponse,
  IdentityCreateParams,
  IdentityCreateResponse,
  IdentityDeleteParams,
  IdentityDuplicateParams,
  IdentityDuplicateResponse,
  IdentityFindParams,
  IdentityFindResponse,
  IdentityGetParams,
  IdentityGetResponse,
  IdentityListParams,
  IdentityListResponse,
  IdentityQueryParams,
  IdentityQueryResponse,
  IdentityRestoreParams,
  IdentityRestoreResponse,
  IdentityUpdateParams,
  IdentityUpdateResponse,
  IdentityUpsertParams,
  IdentityUpsertResponse,
} from './identities';
import * as OrganizationsAPI from './organizations';
import {
  Organization,
  OrganizationBulkCreateParams,
  OrganizationBulkCreateResponse,
  OrganizationBulkDeleteParams,
  OrganizationBulkDeleteResponse,
  OrganizationBulkUpdateParams,
  OrganizationBulkUpdateResponse,
  OrganizationCountParams,
  OrganizationCountResponse,
  OrganizationCreateParams,
  OrganizationCreateResponse,
  OrganizationDeleteParams,
  OrganizationDuplicateParams,
  OrganizationDuplicateResponse,
  OrganizationFindParams,
  OrganizationFindResponse,
  OrganizationGetParams,
  OrganizationGetResponse,
  OrganizationListParams,
  OrganizationListResponse,
  OrganizationQueryParams,
  OrganizationQueryResponse,
  OrganizationRestoreParams,
  OrganizationRestoreResponse,
  OrganizationUpdateParams,
  OrganizationUpdateResponse,
  OrganizationUpsertParams,
  OrganizationUpsertResponse,
  Organizations,
} from './organizations';
import * as ActionsAPI from './actions/actions';
import {
  Action,
  ActionBulkCreateParams,
  ActionBulkCreateResponse,
  ActionBulkDeleteParams,
  ActionBulkDeleteResponse,
  ActionBulkUpdateParams,
  ActionBulkUpdateResponse,
  ActionCountParams,
  ActionCountResponse,
  ActionCreateParams,
  ActionCreateResponse,
  ActionDeleteParams,
  ActionDuplicateParams,
  ActionDuplicateResponse,
  ActionFindParams,
  ActionFindResponse,
  ActionGetParams,
  ActionGetResponse,
  ActionListParams,
  ActionListResponse,
  ActionQueryParams,
  ActionQueryResponse,
  ActionRestoreParams,
  ActionRestoreResponse,
  ActionUpdateParams,
  ActionUpdateResponse,
  ActionUpsertParams,
  ActionUpsertResponse,
  Actions,
} from './actions/actions';
import * as DealsAPI from './deals/deals';
import {
  Deal,
  DealBulkCreateParams,
  DealBulkCreateResponse,
  DealBulkDeleteParams,
  DealBulkDeleteResponse,
  DealBulkUpdateParams,
  DealBulkUpdateResponse,
  DealCountParams,
  DealCountResponse,
  DealCreateParams,
  DealCreateResponse,
  DealDeleteParams,
  DealDuplicateParams,
  DealDuplicateResponse,
  DealFindParams,
  DealFindResponse,
  DealGetParams,
  DealGetResponse,
  DealListParams,
  DealListResponse,
  DealQueryParams,
  DealQueryResponse,
  DealRestoreParams,
  DealRestoreResponse,
  DealUpdateParams,
  DealUpdateResponse,
  DealUpsertParams,
  DealUpsertResponse,
  Deals,
} from './deals/deals';
import * as DocumentsAPI from './documents/documents';
import {
  Document,
  DocumentBulkCreateParams,
  DocumentBulkCreateResponse,
  DocumentBulkDeleteParams,
  DocumentBulkDeleteResponse,
  DocumentBulkUpdateParams,
  DocumentBulkUpdateResponse,
  DocumentCountParams,
  DocumentCountResponse,
  DocumentCreateParams,
  DocumentCreateResponse,
  DocumentDeleteParams,
  DocumentDuplicateParams,
  DocumentDuplicateResponse,
  DocumentFindParams,
  DocumentFindResponse,
  DocumentGetParams,
  DocumentGetResponse,
  DocumentListParams,
  DocumentListResponse,
  DocumentQueryParams,
  DocumentQueryResponse,
  DocumentRestoreParams,
  DocumentRestoreResponse,
  DocumentUpdateParams,
  DocumentUpdateResponse,
  DocumentUpsertParams,
  DocumentUpsertResponse,
  Documents,
} from './documents/documents';
import * as EngagementsAPI from './engagements/engagements';
import {
  Engagement,
  EngagementBulkCreateParams,
  EngagementBulkCreateResponse,
  EngagementBulkDeleteParams,
  EngagementBulkDeleteResponse,
  EngagementBulkUpdateParams,
  EngagementBulkUpdateResponse,
  EngagementCountParams,
  EngagementCountResponse,
  EngagementCreateParams,
  EngagementCreateResponse,
  EngagementDeleteParams,
  EngagementDuplicateParams,
  EngagementDuplicateResponse,
  EngagementFindParams,
  EngagementFindResponse,
  EngagementGetParams,
  EngagementGetResponse,
  EngagementListParams,
  EngagementListResponse,
  EngagementQueryParams,
  EngagementQueryResponse,
  EngagementRestoreParams,
  EngagementRestoreResponse,
  EngagementUpdateParams,
  EngagementUpdateResponse,
  EngagementUpsertParams,
  EngagementUpsertResponse,
  Engagements,
} from './engagements/engagements';
import * as EventsAPI from './events/events';
import {
  Event,
  EventCountParams,
  EventCountResponse,
  EventFindParams,
  EventFindResponse,
  EventGetParams,
  EventGetResponse,
  EventListParams,
  EventListResponse,
  EventQueryParams,
  EventQueryResponse,
  Events,
} from './events/events';

export class Objects extends APIResource {
  contacts: ContactsAPI.Contacts = new ContactsAPI.Contacts(this._client);
  organizations: OrganizationsAPI.Organizations = new OrganizationsAPI.Organizations(this._client);
  identities: IdentitiesAPI.Identities = new IdentitiesAPI.Identities(this._client);
  deals: DealsAPI.Deals = new DealsAPI.Deals(this._client);
  actions: ActionsAPI.Actions = new ActionsAPI.Actions(this._client);
  documents: DocumentsAPI.Documents = new DocumentsAPI.Documents(this._client);
  events: EventsAPI.Events = new EventsAPI.Events(this._client);
  engagements: EngagementsAPI.Engagements = new EngagementsAPI.Engagements(this._client);
}

Objects.Contacts = Contacts;
Objects.Organizations = Organizations;
Objects.Identities = Identities;
Objects.Deals = Deals;
Objects.Actions = Actions;
Objects.Documents = Documents;
Objects.Events = Events;
Objects.Engagements = Engagements;

export declare namespace Objects {
  export {
    Contacts as Contacts,
    type Contact as Contact,
    type ContactCreateResponse as ContactCreateResponse,
    type ContactUpdateResponse as ContactUpdateResponse,
    type ContactListResponse as ContactListResponse,
    type ContactBulkCreateResponse as ContactBulkCreateResponse,
    type ContactBulkDeleteResponse as ContactBulkDeleteResponse,
    type ContactBulkUpdateResponse as ContactBulkUpdateResponse,
    type ContactCountResponse as ContactCountResponse,
    type ContactDuplicateResponse as ContactDuplicateResponse,
    type ContactFindResponse as ContactFindResponse,
    type ContactGetResponse as ContactGetResponse,
    type ContactQueryResponse as ContactQueryResponse,
    type ContactRestoreResponse as ContactRestoreResponse,
    type ContactUpsertResponse as ContactUpsertResponse,
    type ContactCreateParams as ContactCreateParams,
    type ContactUpdateParams as ContactUpdateParams,
    type ContactListParams as ContactListParams,
    type ContactDeleteParams as ContactDeleteParams,
    type ContactBulkCreateParams as ContactBulkCreateParams,
    type ContactBulkDeleteParams as ContactBulkDeleteParams,
    type ContactBulkUpdateParams as ContactBulkUpdateParams,
    type ContactCountParams as ContactCountParams,
    type ContactDuplicateParams as ContactDuplicateParams,
    type ContactFindParams as ContactFindParams,
    type ContactGetParams as ContactGetParams,
    type ContactQueryParams as ContactQueryParams,
    type ContactRestoreParams as ContactRestoreParams,
    type ContactUpsertParams as ContactUpsertParams,
  };

  export {
    Organizations as Organizations,
    type Organization as Organization,
    type OrganizationCreateResponse as OrganizationCreateResponse,
    type OrganizationUpdateResponse as OrganizationUpdateResponse,
    type OrganizationListResponse as OrganizationListResponse,
    type OrganizationBulkCreateResponse as OrganizationBulkCreateResponse,
    type OrganizationBulkDeleteResponse as OrganizationBulkDeleteResponse,
    type OrganizationBulkUpdateResponse as OrganizationBulkUpdateResponse,
    type OrganizationCountResponse as OrganizationCountResponse,
    type OrganizationDuplicateResponse as OrganizationDuplicateResponse,
    type OrganizationFindResponse as OrganizationFindResponse,
    type OrganizationGetResponse as OrganizationGetResponse,
    type OrganizationQueryResponse as OrganizationQueryResponse,
    type OrganizationRestoreResponse as OrganizationRestoreResponse,
    type OrganizationUpsertResponse as OrganizationUpsertResponse,
    type OrganizationCreateParams as OrganizationCreateParams,
    type OrganizationUpdateParams as OrganizationUpdateParams,
    type OrganizationListParams as OrganizationListParams,
    type OrganizationDeleteParams as OrganizationDeleteParams,
    type OrganizationBulkCreateParams as OrganizationBulkCreateParams,
    type OrganizationBulkDeleteParams as OrganizationBulkDeleteParams,
    type OrganizationBulkUpdateParams as OrganizationBulkUpdateParams,
    type OrganizationCountParams as OrganizationCountParams,
    type OrganizationDuplicateParams as OrganizationDuplicateParams,
    type OrganizationFindParams as OrganizationFindParams,
    type OrganizationGetParams as OrganizationGetParams,
    type OrganizationQueryParams as OrganizationQueryParams,
    type OrganizationRestoreParams as OrganizationRestoreParams,
    type OrganizationUpsertParams as OrganizationUpsertParams,
  };

  export {
    Identities as Identities,
    type Identity as Identity,
    type IdentityCreateResponse as IdentityCreateResponse,
    type IdentityUpdateResponse as IdentityUpdateResponse,
    type IdentityListResponse as IdentityListResponse,
    type IdentityBulkCreateResponse as IdentityBulkCreateResponse,
    type IdentityBulkDeleteResponse as IdentityBulkDeleteResponse,
    type IdentityBulkUpdateResponse as IdentityBulkUpdateResponse,
    type IdentityCountResponse as IdentityCountResponse,
    type IdentityDuplicateResponse as IdentityDuplicateResponse,
    type IdentityFindResponse as IdentityFindResponse,
    type IdentityGetResponse as IdentityGetResponse,
    type IdentityQueryResponse as IdentityQueryResponse,
    type IdentityRestoreResponse as IdentityRestoreResponse,
    type IdentityUpsertResponse as IdentityUpsertResponse,
    type IdentityCreateParams as IdentityCreateParams,
    type IdentityUpdateParams as IdentityUpdateParams,
    type IdentityListParams as IdentityListParams,
    type IdentityDeleteParams as IdentityDeleteParams,
    type IdentityBulkCreateParams as IdentityBulkCreateParams,
    type IdentityBulkDeleteParams as IdentityBulkDeleteParams,
    type IdentityBulkUpdateParams as IdentityBulkUpdateParams,
    type IdentityCountParams as IdentityCountParams,
    type IdentityDuplicateParams as IdentityDuplicateParams,
    type IdentityFindParams as IdentityFindParams,
    type IdentityGetParams as IdentityGetParams,
    type IdentityQueryParams as IdentityQueryParams,
    type IdentityRestoreParams as IdentityRestoreParams,
    type IdentityUpsertParams as IdentityUpsertParams,
  };

  export {
    Deals as Deals,
    type Deal as Deal,
    type DealCreateResponse as DealCreateResponse,
    type DealUpdateResponse as DealUpdateResponse,
    type DealListResponse as DealListResponse,
    type DealBulkCreateResponse as DealBulkCreateResponse,
    type DealBulkDeleteResponse as DealBulkDeleteResponse,
    type DealBulkUpdateResponse as DealBulkUpdateResponse,
    type DealCountResponse as DealCountResponse,
    type DealDuplicateResponse as DealDuplicateResponse,
    type DealFindResponse as DealFindResponse,
    type DealGetResponse as DealGetResponse,
    type DealQueryResponse as DealQueryResponse,
    type DealRestoreResponse as DealRestoreResponse,
    type DealUpsertResponse as DealUpsertResponse,
    type DealCreateParams as DealCreateParams,
    type DealUpdateParams as DealUpdateParams,
    type DealListParams as DealListParams,
    type DealDeleteParams as DealDeleteParams,
    type DealBulkCreateParams as DealBulkCreateParams,
    type DealBulkDeleteParams as DealBulkDeleteParams,
    type DealBulkUpdateParams as DealBulkUpdateParams,
    type DealCountParams as DealCountParams,
    type DealDuplicateParams as DealDuplicateParams,
    type DealFindParams as DealFindParams,
    type DealGetParams as DealGetParams,
    type DealQueryParams as DealQueryParams,
    type DealRestoreParams as DealRestoreParams,
    type DealUpsertParams as DealUpsertParams,
  };

  export {
    Actions as Actions,
    type Action as Action,
    type ActionCreateResponse as ActionCreateResponse,
    type ActionUpdateResponse as ActionUpdateResponse,
    type ActionListResponse as ActionListResponse,
    type ActionBulkCreateResponse as ActionBulkCreateResponse,
    type ActionBulkDeleteResponse as ActionBulkDeleteResponse,
    type ActionBulkUpdateResponse as ActionBulkUpdateResponse,
    type ActionCountResponse as ActionCountResponse,
    type ActionDuplicateResponse as ActionDuplicateResponse,
    type ActionFindResponse as ActionFindResponse,
    type ActionGetResponse as ActionGetResponse,
    type ActionQueryResponse as ActionQueryResponse,
    type ActionRestoreResponse as ActionRestoreResponse,
    type ActionUpsertResponse as ActionUpsertResponse,
    type ActionCreateParams as ActionCreateParams,
    type ActionUpdateParams as ActionUpdateParams,
    type ActionListParams as ActionListParams,
    type ActionDeleteParams as ActionDeleteParams,
    type ActionBulkCreateParams as ActionBulkCreateParams,
    type ActionBulkDeleteParams as ActionBulkDeleteParams,
    type ActionBulkUpdateParams as ActionBulkUpdateParams,
    type ActionCountParams as ActionCountParams,
    type ActionDuplicateParams as ActionDuplicateParams,
    type ActionFindParams as ActionFindParams,
    type ActionGetParams as ActionGetParams,
    type ActionQueryParams as ActionQueryParams,
    type ActionRestoreParams as ActionRestoreParams,
    type ActionUpsertParams as ActionUpsertParams,
  };

  export {
    Documents as Documents,
    type Document as Document,
    type DocumentCreateResponse as DocumentCreateResponse,
    type DocumentUpdateResponse as DocumentUpdateResponse,
    type DocumentListResponse as DocumentListResponse,
    type DocumentBulkCreateResponse as DocumentBulkCreateResponse,
    type DocumentBulkDeleteResponse as DocumentBulkDeleteResponse,
    type DocumentBulkUpdateResponse as DocumentBulkUpdateResponse,
    type DocumentCountResponse as DocumentCountResponse,
    type DocumentDuplicateResponse as DocumentDuplicateResponse,
    type DocumentFindResponse as DocumentFindResponse,
    type DocumentGetResponse as DocumentGetResponse,
    type DocumentQueryResponse as DocumentQueryResponse,
    type DocumentRestoreResponse as DocumentRestoreResponse,
    type DocumentUpsertResponse as DocumentUpsertResponse,
    type DocumentCreateParams as DocumentCreateParams,
    type DocumentUpdateParams as DocumentUpdateParams,
    type DocumentListParams as DocumentListParams,
    type DocumentDeleteParams as DocumentDeleteParams,
    type DocumentBulkCreateParams as DocumentBulkCreateParams,
    type DocumentBulkDeleteParams as DocumentBulkDeleteParams,
    type DocumentBulkUpdateParams as DocumentBulkUpdateParams,
    type DocumentCountParams as DocumentCountParams,
    type DocumentDuplicateParams as DocumentDuplicateParams,
    type DocumentFindParams as DocumentFindParams,
    type DocumentGetParams as DocumentGetParams,
    type DocumentQueryParams as DocumentQueryParams,
    type DocumentRestoreParams as DocumentRestoreParams,
    type DocumentUpsertParams as DocumentUpsertParams,
  };

  export {
    Events as Events,
    type Event as Event,
    type EventListResponse as EventListResponse,
    type EventCountResponse as EventCountResponse,
    type EventFindResponse as EventFindResponse,
    type EventGetResponse as EventGetResponse,
    type EventQueryResponse as EventQueryResponse,
    type EventListParams as EventListParams,
    type EventCountParams as EventCountParams,
    type EventFindParams as EventFindParams,
    type EventGetParams as EventGetParams,
    type EventQueryParams as EventQueryParams,
  };

  export {
    Engagements as Engagements,
    type Engagement as Engagement,
    type EngagementCreateResponse as EngagementCreateResponse,
    type EngagementUpdateResponse as EngagementUpdateResponse,
    type EngagementListResponse as EngagementListResponse,
    type EngagementBulkCreateResponse as EngagementBulkCreateResponse,
    type EngagementBulkDeleteResponse as EngagementBulkDeleteResponse,
    type EngagementBulkUpdateResponse as EngagementBulkUpdateResponse,
    type EngagementCountResponse as EngagementCountResponse,
    type EngagementDuplicateResponse as EngagementDuplicateResponse,
    type EngagementFindResponse as EngagementFindResponse,
    type EngagementGetResponse as EngagementGetResponse,
    type EngagementQueryResponse as EngagementQueryResponse,
    type EngagementRestoreResponse as EngagementRestoreResponse,
    type EngagementUpsertResponse as EngagementUpsertResponse,
    type EngagementCreateParams as EngagementCreateParams,
    type EngagementUpdateParams as EngagementUpdateParams,
    type EngagementListParams as EngagementListParams,
    type EngagementDeleteParams as EngagementDeleteParams,
    type EngagementBulkCreateParams as EngagementBulkCreateParams,
    type EngagementBulkDeleteParams as EngagementBulkDeleteParams,
    type EngagementBulkUpdateParams as EngagementBulkUpdateParams,
    type EngagementCountParams as EngagementCountParams,
    type EngagementDuplicateParams as EngagementDuplicateParams,
    type EngagementFindParams as EngagementFindParams,
    type EngagementGetParams as EngagementGetParams,
    type EngagementQueryParams as EngagementQueryParams,
    type EngagementRestoreParams as EngagementRestoreParams,
    type EngagementUpsertParams as EngagementUpsertParams,
  };
}
