// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

export {
  Deals,
  type Deal,
  type DealCreateResponse,
  type DealUpdateResponse,
  type DealListResponse,
  type DealBulkCreateResponse,
  type DealBulkDeleteResponse,
  type DealBulkUpdateResponse,
  type DealCountResponse,
  type DealDuplicateResponse,
  type DealFindResponse,
  type DealGetResponse,
  type DealQueryResponse,
  type DealRestoreResponse,
  type DealUpsertResponse,
  type DealCreateParams,
  type DealUpdateParams,
  type DealListParams,
  type DealDeleteParams,
  type DealBulkCreateParams,
  type DealBulkDeleteParams,
  type DealBulkUpdateParams,
  type DealCountParams,
  type DealDuplicateParams,
  type DealFindParams,
  type DealGetParams,
  type DealQueryParams,
  type DealRestoreParams,
  type DealUpsertParams,
} from './deals';
export {
  Grant,
  type GrantUpdateResponse,
  type GrantGetResponse,
  type GrantUpdateParams,
  type GrantGetParams,
} from './grant';
